---
default_stages: [commit, push, manual]

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
      - id: check-yaml # Attempts to load all yaml files to verify syntax.
      - id: check-json # Attempts to load all json files to verify syntax.
      - id: check-merge-conflict # Check for files that contain merge conflict strings.
      - id: detect-private-key # Checks for the existence of private keys.
      - id: debug-statements # Check for debugger imports and py37+ `breakpoint()` calls in python source.
      - id: check-toml # This hook checks toml files for parseable syntax.
      # - id: no-commit-to-branch # Protect specific branches from direct local commitsß.
      #   args: [--branch, master, --branch, main]

  - repo: https://github.com/pre-commit/pre-commit
    rev: v2.18.1
    hooks:
      - id: validate_manifest

  - repo: https://github.com/asottile/pyupgrade
    rev: v2.32.0
    hooks:
      - id: pyupgrade

  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
        name: black (Formatter)
        language_version: python3 # Should be a command that runs python3.6+

  - repo: https://github.com/pycqa/flake8
    rev: "4.0.1" # pick a git hash / tag to point to
    hooks:
      - id: flake8
        name: flake8 (PEP8 Checker)

  - repo: git@github.com:johnsondnz/pre-commit-coding-standards.git
    rev: v1.1.2
    hooks:
      - id: coding-standards

  - repo: git@github.com:johnsondnz/pre-commit-ansible-lint.git
    rev: v1.0.1
    hooks:
      - id: ansible-lint
      - id: jinja2-lint

  - repo: https://github.com/dnephin/pre-commit-golang
    rev: v0.5.0
    hooks:
      - id: go-fmt
      - id: go-vet
      - id: go-lint
      - id: go-imports
      - id: no-go-testing
      - id: go-unit-tests
      - id: go-build
      - id: go-mod-tidy